lab50:
  window:
    - editor
    - readme
    - terminal
  files:
    - !include mario.py
    - !include README.md

submit50:
  files: &files
    - !exclude "*"
    - !require mario.py

check50:
  files: *files